MarketingSite/MarketingSite/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MarketingSite.Models.Data;
using MarketingSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MarketingSite.Controllers
{
    public class SiteController : Controller
    {
        private readonly AppDbContext db;
        public SiteController(AppDbContext context)
        {
            db = context;
        }
        public IActionResult RequestList(int page = 1)
        {
            var requests = db.Requests.Include(r => r.Application).ToList();

            //Проверка первой и последней страницы
            Page.CheckPage(ref page, requests.Count);

            //Текущая страница для пагинации
            ViewBag.page = page;
            return View(requests.Skip((page - 1) * 10).Take(10));
        }
        public IActionResult ApplicationList(int page = 1)
        {
            var applications = db.Applications.Include(a => a.Requests).ToList();

            // Проверка первой и последней страницы
            Page.CheckPage(ref page, applications.Count);

            //Текущая страница для пагинации
            ViewBag.page = page;

            return View(applications.Skip((page - 1) * 10).Take(10));
        }
        public IActionResult Edit(int id)
        {
            int applicationId = db.Requests.Single(r => r.Id == id).ApplicationId;

            //Выпадающий список с приложениями (отображается название, идентификатор - как передаваемое формой значение),
            //выбранное значение - текущее приложение
            ViewBag.ApplicationId = new SelectList(db.Applications.ToList(), "Id", "Name", applicationId);

            return View(db.Requests.Find(id));
        }
        [HttpPost]
        public ActionResult Edit([Bind("Id,Name,Description,Email,EndOfDevelopment,ApplicationId")] Request request)
        {
            if (ModelState.IsValid)
            {
                //Обновление заявки и сохранение изменений
                db.Update(request);
                db.SaveChanges();
                return RedirectToAction("RequestList");
            }
            return RedirectToAction("Edit", "Request", new { id = request.Id});
        }
        public IActionResult Create()
        {
            //Выпадающий список с приложениями (отображается название, идентификатор - как передаваемое формой значение),
            ViewBag.ApplicationId = new SelectList(db.Applications.ToList(), "Id", "Name");
            return View();
        }
        [HttpPost]
        public ActionResult Create([Bind("Name,Description,Email,EndOfDevelopment,ApplicationId")] Request request)
        {
            if (ModelState.IsValid)
            {
                //Добавление заявки и сохранение изменений
                db.Add(request);
                db.SaveChanges();
                return RedirectToAction("RequestList");
            }
            //Выпадающий список с приложениями (отображается название, идентификатор - как передаваемое формой значение),
            ViewBag.ApplicationId = new SelectList(db.Applications.ToList(), "Id", "Name");
            return View(request);
        }
    }
}

MarketingSite/MarketingSite/Views/Site/ApplicationList.cshtml
@model IEnumerable<MarketingSite.Models.Data.Application>


<h1>Список приложений</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Requests)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Requests, "Requests")
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.ActionLink("Предыдущая страница", "ApplicationList", "Site", new { page = (ViewBag.page-1) }, null) | 
@Html.ActionLink("Следующая страница", "ApplicationList", "Site", new { page = (ViewBag.page+1) }, null) <br />

MarketingSite/MarketingSite/Views/Site/Create.cshtml
@model MarketingSite.Models.Data.Request

@{
    ViewBag.Title = "Edit";
}

<h2>Создать заявку</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    <div id="errorMessages" class="text-danger"></div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @id = "email", required = "required" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndOfDevelopment, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndOfDevelopment, new { htmlAttributes = new { @class = "form-control", @id = "date", required = "required" } })
            @Html.ValidationMessageFor(model => model.EndOfDevelopment, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Фильтровать список приложений</label>
        <div class="col-md-10">
            <input id="filter" type="text" class="form-control" onkeyup="filterSelect()"/>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ApplicationId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ApplicationId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ApplicationId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Принять" class="btn btn-default" />
        </div>
    </div>
</div>
}
@*Валидация даты
  Фильтрация выпадающего списка*@
<script src="~/js/site.js"></script>

MarketingSite/MarketingSite/Views/Site/Edit.cshtml
@model MarketingSite.Models.Data.Request

@{
    ViewBag.Title = "Edit";
}

<h2>Редактировтаь заявку</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @id = "email", required = "required" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndOfDevelopment, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndOfDevelopment, new { htmlAttributes = new { @class = "form-control", @id = "date", required = "required"} })
            @Html.ValidationMessageFor(model => model.EndOfDevelopment, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Фильтровать список приложений</label>
        <div class="col-md-10">
            <input id="filter" type="text" class="form-control" onkeyup="filterSelect()" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ApplicationId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ApplicationId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ApplicationId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Принять" class="btn btn-default" />
        </div>
    </div>
</div>
}
@*Валидация даты
    Фильтрация выпадающего списка*@
<script src="~/js/site.js"></script>

MarketingSite/MarketingSite/Views/Site/RequestList.cshtml
@model IEnumerable<MarketingSite.Models.Data.Request>


<h1>Список заявок</h1>

<p>
    @Html.ActionLink("Добавить заявку", "Create", "Site")
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndOfDevelopment)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Application.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndOfDevelopment)
                </td>
                <td>
                    @Html.ActionLink("Редактировать", "Edit", "Site", new { id = item.Id }, null)
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.ActionLink("Предыдущая страница", "RequestList", "Site", new { page = (ViewBag.page-1) }, null) | 
@Html.ActionLink("Следующая страница", "RequestList", "Site", new { page = (ViewBag.page+1) }, null)<br />